export const dom = {
  hitterTeamFilter: document.querySelector("#team-filter"),
  hitterSearchFilter: document.querySelector("#search-filter"),
  hitterMinPaFilter: document.querySelector("#min-pa-filter"),
  hitterSortKeyFilter: document.querySelector("#sort-key"),
  summaryCards: document.querySelector("#summary-cards"),
  projectionRows: document.querySelector("#projection-rows"),
  teamTitle: document.querySelector("#team-title"),
  teamCopy: document.querySelector("#team-copy"),
  teamMetrics: document.querySelector("#team-metrics"),
  teamLeadersList: document.querySelector("#team-leaders-list"),
  pitcherTeamFilter: document.querySelector("#pitcher-team-filter"),
  pitcherSearchFilter: document.querySelector("#pitcher-search-filter"),
  pitcherMinIpFilter: document.querySelector("#pitcher-min-ip-filter"),
  pitcherSortKeyFilter: document.querySelector("#pitcher-sort-key"),
  pitcherSummaryCards: document.querySelector("#pitcher-summary-cards"),
  pitcherRows: document.querySelector("#pitcher-rows"),
  rosterHitterSlots: document.querySelector("#roster-hitter-slots"),
  rosterPitcherSlots: document.querySelector("#roster-pitcher-slots"),
  rosterSummaryCards: document.querySelector("#roster-summary-cards"),
  rosterTeamStats: document.querySelector("#roster-team-stats"),
  rosterStatus: document.querySelector("#roster-status"),
  rosterAssumption: document.querySelector("#roster-assumption"),
};
